<a href="https://colab.research.google.com/github/arvinsam123/Bootcamp-Colab-Notebooks/blob/main/Module%201/Session%202/m1s2nb1_pandas_groupby_aggregation_FA25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas groupby() and Basic Aggregation

## This is a short (and basic) introduction to groupby() and basic aggregation in pandas.

In [2]:
# some modules we will need
import pandas as pd
import numpy as np

## Let's do a quick introduction of the groupby() function

The pandas `groupby()` function allows you to perform aggregations on groups of your data. The function is typically used to aggregate conditionally on some row label or index. The function is (again) similar in usage to the SQL command `'group by'`.

A `groupby()` operation involves some combination of splitting the object, applying a function, and combining the results. This can be used to group large amounts of data and compute operations on these groups.

#### The basic way to use the function is:

`out = dataframe.groupby(by=columnname).function()`

For example:

`df.groupby(by=["b"]).sum()`

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html

The syntax for the groupby function is fairly straightforward, as most usages simply use the 'by' parameter to designate which column values the data will be grouped on. The function takes the values within the designated column(s) and performs the grouping (and subsequent aggregation).

Under the covers, you can understand the groupby operation as on of split-apply-combine:

1. Split the data into the groups, depending on the specified key value,

2. Apply the aggregation function to each group,

3. Combine the groups back together into a single dataframe.

What `groupby()` on its own does is a dataframe-wide grouping of every APPLICABLE column of the passed-in function, using the "by" parameter that we set.

![split-apply-combine.png](https://github.com/gt-cse-6040/bootcamp/blob/main/Module%201/Session%202/split-apply-combine.png?raw=1)

#### Because `groupby()` is commonly used in conjunction with aggregate functions, we will show examples below.

**VanderPlas has an excellent introduction to groupby in Chapter 3 of his book, available at the below links:**

https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html

https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/03.08-Aggregation-and-Grouping.ipynb

We are only touching on the most basic topics, and VanderPlas goes into great detail through the remainder of this notebook from his book. We encourage you to use this supplemental material in your studies to learn about this function in greater detail.

## Aggregations in Pandas

Pandas supports the normal aggregate functions, such as min, max, mean, median, sum, etc.

By default, aggregation and aggregate functions operate on the columns of the dataframe, or on the series.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sum.html

#### Let's look at some basic examples, performing aggregations on Series objects, which are columns in dataframes.

In [3]:
# for a series
rng = np.random.RandomState(42)  # set a random starting point
agg_series = pd.Series(rng.rand(5))
display(agg_series)

0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
dtype: float64

In [4]:
# aggregate the entire column
display(agg_series.sum())
display(agg_series.mean())

np.float64(2.811925491708157)

np.float64(0.5623850983416314)

#### Now let's look at aggregations on dataframes.

In [5]:
# for a dataframe
df = pd.DataFrame({'A': rng.rand(5),
                   'B': rng.rand(5)})
df

          A         B
0  0.155995  0.020584
1  0.058084  0.969910
2  0.866176  0.832443
3  0.601115  0.212339
4  0.708073  0.181825

If we don't specify an axis argument, the default is to perform the aggregation over the columns.

In [6]:
# aggregate the entire column
df.mean()

A    0.477888
B    0.443420
dtype: float64

By specifying the axis argument, you can instead aggregate within each row:

In [8]:
display(df.sum(axis='columns'))
display(df.mean(axis='columns'))

0    0.176579
1    1.027993
2    1.698619
3    0.813454
4    0.889898
dtype: float64

0    0.088290
1    0.513997
2    0.849309
3    0.406727
4    0.444949
dtype: float64

Here is a listing of aggregates, and all of these operate on both dataframes and series objects. It would be good for you to remember these, and what each of them does.

You can count on most of these appearing on exams in the course.

The following table summarizes some other built-in Pandas aggregations:

| Aggregation              | Description                     |
|--------------------------|---------------------------------|
| ``count()``              | Total number of items           |
| ``first()``, ``last()``  | First and last item             |
| ``mean()``, ``median()`` | Mean and median                 |
| ``min()``, ``max()``     | Minimum and maximum             |
| ``std()``, ``var()``     | Standard deviation and variance |
| ``mad()``                | Mean absolute deviation         |
| ``prod()``               | Product of all items            |
| ``sum()``                | Sum of all items                |

### In general, and in this class, we do aggregate functions on groupings of values within a column, using the `groupby()` function.

Here is a visual example, using `groupby()` and `mean`.

![groupby_1.png](https://github.com/gt-cse-6040/bootcamp/blob/main/Module%201/Session%202/groupby_1.png?raw=1)

In [10]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'data': range(6)}, columns=['key', 'data'])
df

  key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [11]:
# groupby and aggregate by a single column
display(df.groupby('key').sum())
display(df.groupby('key').mean())

     data
key
A       3
B       5
C       7

     data
key
A     1.5
B     2.5
C     3.5

#### What if we want to aggregate by multiple columns?

We can pass a `list` of the columns (that we want to aggregate by) to `groupby()`.

In [13]:
df2 = pd.DataFrame({'key1': ['A', 'B', 'C', 'A', 'B', 'C','A', 'B', 'C', 'A', 'B', 'C'],
                    'key2': ['far', 'far', 'far', 'near', 'near', 'near','far', 'far', 'far', 'near', 'near', 'near'],
                   'data': range(12)}, columns=['key1', 'key2', 'data'])
df2

   key1  key2  data
0     A   far     0
1     B   far     1
2     C   far     2
3     A  near     3
4     B  near     4
5     C  near     5
6     A   far     6
7     B   far     7
8     C   far     8
9     A  near     9
10    B  near    10
11    C  near    11

In [15]:
# groupby and aggregate by multiple columns
display(df2.groupby(['key1','key2']).sum())
display(df2.groupby(['key2','key1']).sum())

           data
key1 key2
A    far      6
     near    12
B    far      8
     near    14
C    far     10
     near    16

           data
key2 key1
far  A        6
     B        8
     C       10
near A       12
     B       14
     C       16

#### Finally, there is a convenience method, describe(), that computes several common aggregates for each column and returns the result. This is good function when you are performing exploratory data analysis (EDA).

In [16]:
df5 = pd.DataFrame({'A': rng.rand(10),
                   'B': rng.rand(10),
                   'C': rng.rand(10),
                   'D': rng.rand(10)})
df5

          A         B         C         D
0  0.183405  0.785176  0.808397  0.662522
1  0.304242  0.199674  0.304614  0.311711
2  0.524756  0.514234  0.097672  0.520068
3  0.431945  0.592415  0.684233  0.546710
4  0.291229  0.046450  0.440152  0.184854
5  0.611853  0.607545  0.122038  0.969585
6  0.139494  0.170524  0.495177  0.775133
7  0.292145  0.065052  0.034389  0.939499
8  0.366362  0.948886  0.909320  0.894827
9  0.456070  0.965632  0.258780  0.597900

In [17]:
df5.describe()

               A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean    0.360150   0.489559   0.415477   0.640281
std     0.148051   0.351583   0.306710   0.262852
min     0.139494   0.046450   0.034389   0.184854
25%     0.291458   0.177812   0.156224   0.526729
50%     0.335302   0.553325   0.372383   0.630211
75%     0.450039   0.740768   0.636969   0.864904
max     0.611853   0.965632   0.909320   0.969585

**This concludes our (basic) introduction to `groupby()` and `aggregation` in pandas.**

**We encourage you to delve deeper into them, as you will be using all of these throughout this class and professionally in working with Python for Analytics.**

**We also highly encourage you to work through NB7 Part1, the FEC Dataset notebook, as is does a full analysis of 'real life' data from the Federal Election Commission, including application of most of the above functions that we have covered here.**